# Problem 1 

In [1]:
import numpy as np

def sirali_array_olustur():
    # 5 elemanlı bir numpy array oluşturun
    dizi = np.array([5, 3, 1, 4, 2])
    
    # Array'i küçükten büyüğe sıralayın
    sirali_dizi = np.sort(dizi)
    
    return sirali_dizi

# Fonksiyonu çağırarak sonucu yazdırın
print(sirali_array_olustur())

[1 2 3 4 5]


# Problem 2

In [2]:
import numpy as np

def numpy_islemleri():
    # 1 - (10, 15, 30, 45, 60) değerlerine sahip numpy dizisi oluşturun
    dizi1 = np.array([10, 15, 30, 45, 60])
    
    # 2 - (5-15) arasındaki sayılarla numpy dizisi oluşturun
    dizi2 = np.arange(5, 16)
    
    # 3 - (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturun
    dizi3 = np.arange(50, 101, 5)
    
    # 4 - 10 elemanlı sıfırlardan oluşan bir dizi oluşturun
    dizi4 = np.zeros(10)
    
    # 5 - 10 elemanlı birlerden oluşan bir dizi oluşturun
    dizi5 = np.ones(10)
    
    # 6 - (0-100) arasında eşit aralıklı 5 sayı üretin
    dizi6 = np.linspace(0, 100, 5)
    
    # 7 - (10-30) arasında rastgele 5 tane tamsayı üretin
    dizi7 = np.random.randint(10, 31, size=5)
    
    # 8 - [-1 ile 1] arasında 10 adet sayı üretin
    dizi8 = np.random.uniform(-1, 1, size=10)
    
    # 9 - (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturun
    matris = np.random.randint(10, 51, size=(3, 5))
    
    # 10 - Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayın
    satir_sayisi, sutun_sayisi = matris.shape
    toplam = satir_sayisi + sutun_sayisi
    
    # 11 - Üretilen matrisin en büyük, en küçük ve ortalamasını hesaplayın
    en_büyük = np.max(matris)
    en_küçük = np.min(matris)
    ortalama = np.mean(matris)
    
    # 12 - Üretilen matrisin en büyük değerinin indeksini bulun
    en_büyük_indeks = np.unravel_index(np.argmax(matris), matris.shape)
    
    # 13 - (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçin
    dizi13 = np.arange(10, 21)[:3]
    
    # 14 - Üretilen dizinin elemanlarını tersten yazdırın
    tersten_dizi13 = dizi13[::-1]
    
    # 15 - Üretilen matrisin ilk satırını seçin
    ilk_satir = matris[0]
    
    # 16 - Üretilen matrisin 2. satır 3. sütundaki elemanı
    eleman = matris[1, 2]
    
    # 17 - Üretilen matrisin tüm satırlardaki ilk elemanı seçin
    ilk_elemanlar = matris[:, 0]
    
    # 18 - Üretilen matrisin her bir elemanının karesini alın
    karesini_al = np.power(matris, 2)
    
    # 19 - Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız
    matris2 = np.random.randint(-50, 51, size=(3, 5))
    pozitif_ciftler = matris2[(matris2 > 0) & (matris2 % 2 == 0)]
    
    return {
        'dizi1': dizi1,
        'dizi2': dizi2,
        'dizi3': dizi3,
        'dizi4': dizi4,
        'dizi5': dizi5,
        'dizi6': dizi6,
        'dizi7': dizi7,
        'dizi8': dizi8,
        'matris': matris,
        'toplam': toplam,
        'en_büyük': en_büyük,
        'en_küçük': en_küçük,
        'ortalama': ortalama,
        'en_büyük_indeks': en_büyük_indeks,
        'ilk_3_eleman': dizi13,
        'tersten_dizi': tersten_dizi13,
        'ilk_satir': ilk_satir,
        '2_3_eleman': eleman,
        'ilk_elemanlar': ilk_elemanlar,
        'karesini_al': karesini_al,
        'pozitif_ciftler': pozitif_ciftler
    }

# Fonksiyonu çağırarak sonuçları yazdırın
sonuclar = numpy_islemleri()
for anahtar, deger in sonuclar.items():
    print(f"{anahtar}: {deger}")

dizi1: [10 15 30 45 60]
dizi2: [ 5  6  7  8  9 10 11 12 13 14 15]
dizi3: [ 50  55  60  65  70  75  80  85  90  95 100]
dizi4: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
dizi5: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
dizi6: [  0.  25.  50.  75. 100.]
dizi7: [19 13 16 16 22]
dizi8: [ 0.58175157  0.20378601 -0.28881924  0.64756582  0.73401932 -0.35832723
 -0.98562641  0.55283368  0.00946921 -0.48206688]
matris: [[25 36 14 13 22]
 [20 21 50 30 36]
 [12 14 38 20 36]]
toplam: 8
en_büyük: 50
en_küçük: 12
ortalama: 25.8
en_büyük_indeks: (np.int64(1), np.int64(2))
ilk_3_eleman: [10 11 12]
tersten_dizi: [12 11 10]
ilk_satir: [25 36 14 13 22]
2_3_eleman: 50
ilk_elemanlar: [25 20 12]
karesini_al: [[ 625 1296  196  169  484]
 [ 400  441 2500  900 1296]
 [ 144  196 1444  400 1296]]
pozitif_ciftler: [48 26 48 50 48]
